FROM golang:1.21 AS builder

WORKDIR /usr/src/app

COPY go.mod ./
COPY . .

RUN go build -v -o /usr/local/bin/app ./...

RUN apt-get purge -y --auto-remove && \
    rm -rf /var/lib/apt/lists/*

RUN go clean -cache -modcache

FROM scratch
COPY --from=builder /usr/local/bin/app /usr/local/bin/app

CMD ["app"]
